version: "3"
services:
  db:
    container_name: postgres-taskMaster
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: taskMaster_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    hostname: redis
    image: redis:alpine
    ports:
        - "6379:6379"

  nginx:
    container_name: nginx-taskMaster
    build: ./nginx
    ports:
    - "80:80"
    depends_on:
      - frontend
      - backend

  worker:
    container_name: celery-taskMaster
    build: 
      context: ./backend
      dockerfile: ./celeryUtil/Dockerfile    
    links:
        - redis
    depends_on:
        - redis
        - backend
    volumes:
      - ./backend:/backend
    command: celery -A app.celery worker --loglevel=info
      
  backend:
    container_name: flask-taskMaster
    build: ./backend
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/backend
  
  frontend:
    container_name: angular-taskMaster
    build: ./frontend
    ports:
          - '4200:4200'
    restart: always
    volumes: 
        - './frontend:/frontend'
