FROM python:3.9.1

# MAINTAINER Arjun TR "arjuntrh@gmail.com"

# RUN apt-get update -y && \
#     apt-get install -y python3-pip python3-dev

WORKDIR /backend

COPY . .

RUN pip3 install -r requirements.txt